### PR TITLE
feat(langchain): update langchain and related tests

### PR DESCRIPTION
**Pull request by pilartomas**

### CODE REVIEW

**Review by Tomas2D — CHANGES_REQUESTED** [review]
- Update `tokenUsage` structure to match Langchain standard.
- Rewrite `llm-chat.ts` to start using /v2/text/chat endpoint
- Do not ignore the moderation chunk during streaming!

**Comment by pilartomas** [comment]
- Rewrite llm-chat.ts to start using /v2/text/chat endpoint

I had a look and it will be quite complex to do properly. Please create an issue since it is out of scope.

**Comment by Tomas2D** [comment]
We want to release the correct chat functionality before the v2 release.

**Review by Tomas2D — APPROVED** [review]
Create LangChain Chat implementation in a new PR.

**Pull request merged**
